//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityCarrito
    {
        public EntityCarrito()
        {
   
        }
    
        public int idCarrito { get; set; }
        public decimal Total { get; set; }
        public int EstadoCarrito_idEstadoCarrito { get; set; }

        public virtual EntityEstadoCarrito EstadoCarrito { get; set; }
        public virtual ICollection<EntityPedido> Pedido { get; set; }
        public virtual ICollection<EntityProductoCarrito> ProductoCarrito { get; set; }
    }
}
