//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class EntityEstadoPedido
    {
        public EntityEstadoPedido() { }
        public EntityEstadoPedido(int idEstadoPedido, string nombre, string descripcion)
        {
            IdEstadoPedido = idEstadoPedido;
            Nombre = nombre;
            Descripcion = descripcion;
        }

        [Column("idEstadoPedido")]
        public int IdEstadoPedido { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public virtual ICollection<EntityPedido> Pedido { get; set; }
    }
}
