//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class EntityDetallePedido
    {
        public EntityDetallePedido() { }
        public EntityDetallePedido(DateTime fechaPedido, DateTime fechaEntrega, int idFormaEntrega, int idFormaPago, int idDireccion,int idPedido)
        {
            Pedido_idPedido = idPedido;
            FechaPedido = fechaPedido;
            FechaEntrega = fechaEntrega;
            FormaEntrega_idFormaEntrega = idFormaEntrega;
            FormaPago_idFormaPago = idFormaPago;
            Direccion_idDireccion = idDireccion;
        }
        public int Pedido_idPedido { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public int FormaEntrega_idFormaEntrega { get; set; }
        public int FormaPago_idFormaPago { get; set; }
        public Nullable<int> Direccion_idDireccion { get; set; }
        public virtual EntityDireccion Direccion { get; set; }
        public virtual EntityFormaEntrega FormaEntrega { get; set; }
        public virtual EntityFormaPago FormaPago { get; set; }
        public virtual EntityPedido Pedido { get; set; }
    }
}
