//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class EntityProducto
    {
        public EntityProducto() { }
        public EntityProducto(int idProducto, string nombre, string descripcion, decimal precio, int stock, bool estado, int idMarca,List<EntityImagen> Imagenes, List<EntityCategoria> Categorias, List<EntityProveedor> Proveedores)
        {
            IdProducto = idProducto;
            Nombre = nombre;
            Descripcion = descripcion;
            Precio = precio;
            Stock = stock;
            Estado = estado;
            Marca_idMarca = idMarca;
            Imagen = Imagenes;
            Categoria = Categorias;
            Proveedor = Proveedores;
        }

        [Column("idProducto")]
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int Stock { get; set; }
        public bool Estado { get; set; }
        public int Marca_idMarca { get; set; }
    
        public virtual EntityMarca Marca { get; set; }
        public virtual ICollection<EntityProductoCarrito> ProductoCarrito { get; set; }
        public virtual ICollection<EntityImagen> Imagen { get; set; }
        public virtual ICollection<EntityCategoria> Categoria { get; set; }
        public virtual ICollection<EntityProveedor> Proveedor { get; set; }
    }
}
