//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class EntityPersona
    {
        public EntityPersona() { }
        public EntityPersona(int idPersona, string nombre, string apellido, string mail, string telefono, int idUsuario, List<EntityDireccion> Direcciones)
        {
            IdPersona = idPersona;
            Nombre = nombre;
            Apellido = apellido;
            Mail = mail;
            Telefono = telefono;
            Usuario_idUsuario = idUsuario;
            Direccion = Direcciones;
        }

        [Column("idPersona")]
        public int IdPersona { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public int Usuario_idUsuario { get; set; }
        public virtual ICollection<EntityPedido> Pedido { get; set; }
        public virtual EntityUsuario Usuario { get; set; }
        public virtual ICollection<EntityDireccion> Direccion { get; set; }
    }
}
