//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class EntityUsuario
    {
        public EntityUsuario() { }
        public EntityUsuario(int idUsuario, string Nombre, string contraseña, bool estado, int rol)
        {
            IdUsuario = idUsuario;
            NombreUsuario = Nombre;
            Contraseña = contraseña;
            Estado = estado;
            Rol = rol;
        }

        [Column("idUsuario")]
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }

        [Column("Contrase\u00C3\u00B1a")]
        public string Contraseña { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<EntityPersona> Persona { get; set; }
        [Column("Rol_idRol")]
        public int Rol { get; set; }
    }
}
