//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class EntityProveedor
    {
        public EntityProveedor() { }
        public EntityProveedor(int idProveedor, string nombre, string telefono, string mail, bool estado, int idDireccion)
        {
            IdProveedor = idProveedor;
            Nombre = nombre;
            Telefono = telefono;
            Mail = mail;
            Estado = estado;
            Direccion_idDireccion = idDireccion;
        }

        [Column("idProveedor")]
        public int IdProveedor { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public bool Estado { get; set; }
        public int Direccion_idDireccion { get; set; }
    
        public virtual EntityDireccion Direccion { get; set; }
        public virtual ICollection<EntityProducto> Producto { get; set; }
    }
}
