//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EntityDireccion
    {
        public EntityDireccion() { }
        public EntityDireccion(int idDireccion, string calle, string numero, string localidad, string codigoPostal, string observaciones)
        {
            IdDireccion = idDireccion;
            Calle = calle;
            Numero = numero;
            Localidad = localidad;
            CodigoPostal = codigoPostal;
            Observaciones = observaciones;
        }

        [Column("idDireccion")]
        public int IdDireccion { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Localidad { get; set; }
        public string CodigoPostal { get; set; }
        public string Observaciones { get; set; }
        public virtual ICollection<EntityDetallePedido> DetallePedido { get; set; }
        public virtual ICollection<EntityProveedor> Proveedor { get; set; }
        public virtual ICollection<EntityPersona> Persona { get; set; }
    }
}
