//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class EntityImagen
    {
        public EntityImagen() { }
        public EntityImagen(int idImagen, string nombre, string descripcion, string Url)
        {
            IdImagen = idImagen;
            Nombre = nombre;
            Descripcion = descripcion;
            URL = Url;
        }

        [Column("idImagen")]
        public int IdImagen { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string URL { get; set; }
        public virtual ICollection<EntityMarca> Marca { get; set; }
        public virtual ICollection<EntityProducto> Producto { get; set; }
    }
}
