//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityFormaEntrega
    {

        public EntityFormaEntrega()
        {
            this.DetallePedido = new HashSet<EntityDetallePedido>();
        }
    
        public int idFormaEntrega { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public virtual ICollection<EntityDetallePedido> DetallePedido { get; set; }
    }
}
