//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntityCarrito> Carrito { get; set; }
        public virtual DbSet<EntityCategoria> Categoria { get; set; }
        public virtual DbSet<EntityDetallePedido> DetallePedido { get; set; }
        public virtual DbSet<EntityDireccion> Direccion { get; set; }
        public virtual DbSet<EntityEstadoCarrito> EstadoCarrito { get; set; }
        public virtual DbSet<EntityEstadoPedido> EstadoPedido { get; set; }
        public virtual DbSet<EntityFormaEntrega> FormaEntrega { get; set; }
        public virtual DbSet<EntityFormaPago> FormaPago { get; set; }
        public virtual DbSet<EntityImagen> Imagen { get; set; }
        public virtual DbSet<EntityMarca> Marca { get; set; }
        public virtual DbSet<EntityPedido> Pedido { get; set; }
        public virtual DbSet<EntityPermiso> Permiso { get; set; }
        public virtual DbSet<EntityPersona> Persona { get; set; }
        public virtual DbSet<EntityProducto> Producto { get; set; }
        public virtual DbSet<EntityProductoCarrito> ProductoCarrito { get; set; }
        public virtual DbSet<EntityProveedor> Proveedor { get; set; }
        public virtual DbSet<EntityRol> Rol { get; set; }
        public virtual DbSet<EntityUsuario> Usuario { get; set; }
    }
}
