//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityPedido
    {
        public int idPedido { get; set; }
        public int Persona_idPersona { get; set; }
        public int EstadoPedido_idEstadoPedido { get; set; }
        public int Carrito_idCarrito { get; set; }
    
        public virtual EntityCarrito Carrito { get; set; }
        public virtual EntityDetallePedido DetallePedido { get; set; }
        public virtual EntityEstadoPedido EstadoPedido { get; set; }
        public virtual EntityPersona Persona { get; set; }
    }
}
