//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityPermiso
    {

        public EntityPermiso() { }
        public EntityPermiso(int idPermiso, string nombre)
        {
            IdPermiso = idPermiso;
            Nombre = nombre;
        }

        public int IdPermiso { get; set; }
        public string Nombre { get; set; }
    

        public virtual ICollection<EntityRol> Rol { get; set; }
    }
}
