//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityProveedor
    {
 
        public EntityProveedor()
        {
           
        }
    
        public int idProveedor { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Mail { get; set; }
        public bool Estado { get; set; }
        public int Direccion_idDireccion { get; set; }
    
        public virtual EntityDireccion Direccion { get; set; }
    
        public virtual ICollection<EntityProducto> Producto { get; set; }
    }
}
