//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityRol
    {

        public EntityRol() { }
        public EntityRol(int idRol, string nombre)
        {
            IdRol = idRol;
            Nombre = nombre;
        }

        public int IdRol { get; set; }
        public string Nombre { get; set; }
        public virtual ICollection<EntityUsuario> Usuario { get; set; }
        public virtual ICollection<EntityPermiso> Permiso { get; set; }
    }
}
