//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityUsuario
    {
        
        public EntityUsuario()
        {
            
        }
    
        public int idUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public bool Estado { get; set; }
        public int Rol_idRol { get; set; }
    
       
        public virtual ICollection<EntityPersona> Persona { get; set; }
        public virtual EntityRol Rol { get; set; }
    }
}
